services:
  frontend:
    build:
      context: ./frontend-calc-prob-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend-calc-prob-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app-network
    volumes:
      - backend-logs:/app/logs  # Use named volume instead of bind mount
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Loki for log aggregation
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - app-network

  # Promtail to ship logs to Loki
  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yml
      - backend-logs:/app/logs:ro  # Mount the same named volume as backend
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-network
    depends_on:
      - loki

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3001:3000"  # Using 3001 to avoid conflict with your frontend
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SECURITY_ADMIN_USER=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_LOG_LEVEL=debug
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - app-network
    depends_on:
      - loki

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
  backend-logs:  # Add named volume for logs
  loki-data:
  grafana-data:
