server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # Your application calculation logs
  - job_name: app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-calculations
          __path__: /app/logs/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: Date
            level: IsError
            calculation: Calculation
            inputs: Inputs
            result: Result
      - labels:
          level:
          calculation:
      - timestamp:
          format: "2006-01-02 15:04:05 UTC"
          source: timestamp
