name: Frontend Code Quality

on:
  push:
    branches: [main]
    paths: ["frontend-calc-prob-app/**"]
  pull_request:
    branches: [main]
    paths: ["frontend-calc-prob-app/**"]

jobs:
  frontend-quality:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend-calc-prob-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check Prettier formatting
        run: bun run format:check

      - name: Run ESLint
        run: bun run lint

      - name: Type check
        run: bun run tsc --noEmit

      - name: Build project
        run: bun run build
